- name: Copy sshd banner
  tags: ssh-banner-copy
  copy:
    src: banner
    dest: /etc/issue
    mode: 444
    owner: root
    group: bin
  notify: "Restart ssh service"

- name: Set banner file in sshd_config
  tags: ssh-banner-config
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: 'Banner'
    line: 'Banner /etc/issue'
  notify: "Restart ssh service"
